"""Add User, EvidenceImage, and VerificationLog models

Revision ID: d4ec90d5f606
Revises: 
Create Date: 2026-02-02 16:00:45.310815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4ec90d5f606'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_path', sa.String(length=512), nullable=False),
    sa.Column('watermarked_path', sa.String(length=512), nullable=True),
    sa.Column('original_hash', sa.String(length=64), nullable=False),
    sa.Column('watermarked_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'VERIFIED', 'TAMPERED', 'FAILED', name='imagestatus'), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('exif_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_images_id'), 'evidence_images', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_images_user_id'), 'evidence_images', ['user_id'], unique=False)
    op.create_table('verification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('is_authentic', sa.Boolean(), nullable=False),
    sa.Column('is_tampered', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('verification_type', sa.String(length=50), nullable=False),
    sa.Column('tampered_regions', sa.Text(), nullable=True),
    sa.Column('tampering_severity', sa.String(length=20), nullable=True),
    sa.Column('extracted_payload', sa.Text(), nullable=True),
    sa.Column('payload_match', sa.Boolean(), nullable=True),
    sa.Column('verified_by_user_id', sa.Integer(), nullable=True),
    sa.Column('request_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('algorithm_version', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['evidence_images.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_logs_id'), 'verification_logs', ['id'], unique=False)
    op.create_index(op.f('ix_verification_logs_image_id'), 'verification_logs', ['image_id'], unique=False)
    op.create_index(op.f('ix_verification_logs_verified_by_user_id'), 'verification_logs', ['verified_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_logs_verified_by_user_id'), table_name='verification_logs')
    op.drop_index(op.f('ix_verification_logs_image_id'), table_name='verification_logs')
    op.drop_index(op.f('ix_verification_logs_id'), table_name='verification_logs')
    op.drop_table('verification_logs')
    op.drop_index(op.f('ix_evidence_images_user_id'), table_name='evidence_images')
    op.drop_index(op.f('ix_evidence_images_id'), table_name='evidence_images')
    op.drop_table('evidence_images')
    # ### end Alembic commands ###
